name: build
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches: [ main ]
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.18', '1.17' ]

    name: go run ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - run: go run cmd/usanamegen/usanamegen.go naive
