name: lint
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches: [ main ]
  schedule:
    - cron: 0 0 * * *

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.18', '1.17' ]
        golangci: [ 'latest', 'v1.47.2' ]  # https://github.com/golangci/golangci-lint/releases
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ matrix.golangci }}
          skip-cache: true
          skip-pkg-cache: true
          skip-build-cache: true
